site_name: Pomo Docs
nav:
      - Home: index.md
      - Desenho de Software:
            - Base:
                  - 1.1 Módulo Projeto Não Orientado a Abordagens Específicas:
                        - 5W2H: base/modulo1.1/5w2h.md
                        - Rich Picture: base/modulo1.1/richpicture.md
                  
theme:
  name: material