site_name: Pomo Docs
nav:
  - Home: index.md
  - Desenho de Software:
      - Base:
          - 1.1 Módulo Projeto Não Orientado a Abordagens Específicas:
              - 5W2H: base/modulo1.1/5w2h.md
              - Rich Picture: base/modulo1.1/richpicture.md
              - Diagrama de causa e efeito: base/modulo1.1/causa_efeito.md
              - Mapa Mental: base/modulo1.1/mapa_mental.md
              - Questionario: base/modulo1.1/questionario.md
              - Estimativas: base/modulo1.1/estimativas.md
              - Plano de Risco: base/modulo1.1/PlanoDeRisco.md
              - Brainstorm: base/modulo1.1/brainstorm.md
              - Introspecção: base/modulo1.1/introspeccao.md
              - Priorização: base/modulo1.1/priorizacao.md
              - Léxico: base/modulo1.1/lexico.md
              - Backlog: base/modulo1.1/backlog.md

          - 1.2 Módulo Processos/Metodologias/Abordagens (Apresentação):
              - Metodologia: base/modulo1.2/metodologia.md

          - 1.3 Módulo Processos/Metodologias/Abordagens (Modelagem BPMN):
              - BPMN'S: base/modulo1.3/bpmn.md
      - Modelagem:
          - 2.1 Módulo Projeto Orientado a Abordagens Tradicionais:
              - 2.1.1 Notação UML - Diagramas Estáticos:
                  - Diagrama de Componentes: modelagem/modulo2.1/diagramacomponentes.md
                  - Diagrama de Pacotes: modelagem/modulo2.1/diagrama_de_pacotes.md
                  - Diagrama de Classes: modelagem/modulo2.1/diagrama_de_classes.md
              - 2.1.2 Notação UML - Diagramas Dinâmicos:
                  - Diagrama de Estados: modelagem/modulo2.2/diagrama_estados.md
                  - Diagrama de Atividades: modelagem/modulo2.2/diagrama_atividades.md
      - Padrões de projeto:
          - 3.1 GRASPs: padrões-de-projeto/modulo3.0/grasps.md
          - GoFs:
              - 3.2 GoFs Criacionais: padrões-de-projeto/modulo3.1/gofs_criacionais.md
              - 3.3 GoFs Estruturais: padrões-de-projeto/modulo3.3/gofs_estruturais.md
              - 3.4 GoFs Comportamentais: padrões-de-projeto/modulo3.4/gofs_comportamentais.md
          - Padrões Emergentes: padrões-de-projeto/modulo3.5/padroes_emergentes.md

      - Arquitetura e Reutilização de Software:
          - Documento de Arquitetura: arquitetura-e-reutilizacao/arquitetura.md
          - Documento de Reutilização: arquitetura-e-reutilizacao/reutilizacao.md
  - Templates:
      - Issue:
          - Bug report: base/templates/ISSUE_TEMPLATE/template_bug_report.md
          - Nova feature: base/templates/ISSUE_TEMPLATE/template_para_nova_feature.md
      - Pull Request:
          - Bug report: base/templates/PULL_REQUEST_TEMPLATE/template_bug_report.md
          - Nova feature: base/templates/PULL_REQUEST_TEMPLATE/template_para_nova_feature.md
      - Commit:
          - Bug report: base/templates/COMMIT_TEMPLATE/template_bug_report.md
          - Nova feature: base/templates/COMMIT_TEMPLATE/template_para_nova_feature.md
          - Doc: base/templates/COMMIT_TEMPLATE/template_doc.md
  - Extra:
      - Prototipação:
          - Baixa Fidelidade: extra/prototipos/baixa_fidelidade.md
          - Alta Fidelidade: extra/prototipos/alta_fidelidade.md
      - Relatórios de Sprint:
          - Sprint 2:
              - Planning: extra/relatorios/sprint2/planning.md
              - Review: extra/relatorios/sprint2/review.md

theme:
  name: material
  language: "pt"
  # logo:
  #   icon: 'phone_iphone'
  palette:
    primary: "red"
    accent: "pink"

repo_name: "Pomo"
repo_url: "https://github.com/UnBArqDsw/2020.1_G6_Pomo"
